export interface City {
  slug: string;
  name: string;
  state: string;
  population: number;
}

export const CITIES: City[] = [
  { slug: "berlin", name: "Berlin", state: "Berlin", population: 3645000 },
  { slug: "hamburg", name: "Hamburg", state: "Hamburg", population: 1841000 },
  { slug: "muenchen", name: "München", state: "Bayern", population: 1472000 },
  { slug: "koeln", name: "Köln", state: "Nordrhein-Westfalen", population: 1084000 },
  { slug: "frankfurt", name: "Frankfurt am Main", state: "Hessen", population: 753000 },
  { slug: "stuttgart", name: "Stuttgart", state: "Baden-Württemberg", population: 632000 },
  { slug: "duesseldorf", name: "Düsseldorf", state: "Nordrhein-Westfalen", population: 619000 },
  { slug: "leipzig", name: "Leipzig", state: "Sachsen", population: 587000 },
  { slug: "dortmund", name: "Dortmund", state: "Nordrhein-Westfalen", population: 588000 },
  { slug: "essen", name: "Essen", state: "Nordrhein-Westfalen", population: 582000 },
  { slug: "bremen", name: "Bremen", state: "Bremen", population: 563000 },
  { slug: "dresden", name: "Dresden", state: "Sachsen", population: 556000 },
  { slug: "hannover", name: "Hannover", state: "Niedersachsen", population: 532000 },
  { slug: "nuernberg", name: "Nürnberg", state: "Bayern", population: 515000 },
  { slug: "duisburg", name: "Duisburg", state: "Nordrhein-Westfalen", population: 498000 },
  { slug: "bochum", name: "Bochum", state: "Nordrhein-Westfalen", population: 365000 },
  { slug: "wuppertal", name: "Wuppertal", state: "Nordrhein-Westfalen", population: 355000 },
  { slug: "bielefeld", name: "Bielefeld", state: "Nordrhein-Westfalen", population: 333000 },
  { slug: "bonn", name: "Bonn", state: "Nordrhein-Westfalen", population: 329000 },
  { slug: "muenster", name: "Münster", state: "Nordrhein-Westfalen", population: 316000 },
  { slug: "mannheim", name: "Mannheim", state: "Baden-Württemberg", population: 309000 },
  { slug: "karlsruhe", name: "Karlsruhe", state: "Baden-Württemberg", population: 308000 },
  { slug: "augsburg", name: "Augsburg", state: "Bayern", population: 296000 },
  { slug: "wiesbaden", name: "Wiesbaden", state: "Hessen", population: 279000 },
  { slug: "gelsenkirchen", name: "Gelsenkirchen", state: "Nordrhein-Westfalen", population: 260000 },
  { slug: "moenchengladbach", name: "Mönchengladbach", state: "Nordrhein-Westfalen", population: 261000 },
  { slug: "braunschweig", name: "Braunschweig", state: "Niedersachsen", population: 249000 },
  { slug: "chemnitz", name: "Chemnitz", state: "Sachsen", population: 247000 },
  { slug: "kiel", name: "Kiel", state: "Schleswig-Holstein", population: 246000 },
  { slug: "aachen", name: "Aachen", state: "Nordrhein-Westfalen", population: 245000 },
  { slug: "halle", name: "Halle (Saale)", state: "Sachsen-Anhalt", population: 239000 },
  { slug: "magdeburg", name: "Magdeburg", state: "Sachsen-Anhalt", population: 237000 },
  { slug: "freiburg", name: "Freiburg im Breisgau", state: "Baden-Württemberg", population: 229000 },
  { slug: "krefeld", name: "Krefeld", state: "Nordrhein-Westfalen", population: 228000 },
  { slug: "luebeck", name: "Lübeck", state: "Schleswig-Holstein", population: 216000 },
  { slug: "oberhausen", name: "Oberhausen", state: "Nordrhein-Westfalen", population: 210000 },
  { slug: "erfurt", name: "Erfurt", state: "Thüringen", population: 213000 },
  { slug: "mainz", name: "Mainz", state: "Rheinland-Pfalz", population: 218000 },
  { slug: "rostock", name: "Rostock", state: "Mecklenburg-Vorpommern", population: 209000 },
  { slug: "kassel", name: "Kassel", state: "Hessen", population: 201000 },
  { slug: "hagen", name: "Hagen", state: "Nordrhein-Westfalen", population: 189000 },
  { slug: "potsdam", name: "Potsdam", state: "Brandenburg", population: 183000 },
  { slug: "saarbruecken", name: "Saarbrücken", state: "Saarland", population: 180000 },
  { slug: "hamm", name: "Hamm", state: "Nordrhein-Westfalen", population: 179000 },
  { slug: "ludwigshafen", name: "Ludwigshafen am Rhein", state: "Rheinland-Pfalz", population: 172000 },
  { slug: "oldenburg", name: "Oldenburg", state: "Niedersachsen", population: 168000 },
  { slug: "muelhein-ruhr", name: "Mülheim an der Ruhr", state: "Nordrhein-Westfalen", population: 171000 },
  { slug: "osnabrueck", name: "Osnabrück", state: "Niedersachsen", population: 165000 },
  { slug: "leverkusen", name: "Leverkusen", state: "Nordrhein-Westfalen", population: 163000 },
  { slug: "heidelberg", name: "Heidelberg", state: "Baden-Württemberg", population: 159000 },
  { slug: "darmstadt", name: "Darmstadt", state: "Hessen", population: 158000 },
  { slug: "solingen", name: "Solingen", state: "Nordrhein-Westfalen", population: 158000 },
  { slug: "herne", name: "Herne", state: "Nordrhein-Westfalen", population: 155000 },
  { slug: "neuss", name: "Neuss", state: "Nordrhein-Westfalen", population: 151000 },
  { slug: "regensburg", name: "Regensburg", state: "Bayern", population: 153000 },
  { slug: "paderborn", name: "Paderborn", state: "Nordrhein-Westfalen", population: 151000 },
  { slug: "ingolstadt", name: "Ingolstadt", state: "Bayern", population: 138000 },
  { slug: "offenbach", name: "Offenbach am Main", state: "Hessen", population: 130000 },
  { slug: "fuerth", name: "Fürth", state: "Bayern", population: 128000 },
  { slug: "ulm", name: "Ulm", state: "Baden-Württemberg", population: 126000 },
  { slug: "heilbronn", name: "Heilbronn", state: "Baden-Württemberg", population: 126000 },
  { slug: "pforzheim", name: "Pforzheim", state: "Baden-Württemberg", population: 124000 },
  { slug: "wuerzburg", name: "Würzburg", state: "Bayern", population: 127000 },
  { slug: "wolfsburg", name: "Wolfsburg", state: "Niedersachsen", population: 124000 },
  { slug: "goettingen", name: "Göttingen", state: "Niedersachsen", population: 119000 },
  { slug: "recklinghausen", name: "Recklinghausen", state: "Nordrhein-Westfalen", population: 115000 },
  { slug: "bottrop", name: "Bottrop", state: "Nordrhein-Westfalen", population: 117000 },
  { slug: "bremerhaven", name: "Bremerhaven", state: "Bremen", population: 113000 },
  { slug: "reutlingen", name: "Reutlingen", state: "Baden-Württemberg", population: 115000 },
  { slug: "koblenz", name: "Koblenz", state: "Rheinland-Pfalz", population: 114000 },
  { slug: "erlangen", name: "Erlangen", state: "Bayern", population: 112000 },
  { slug: "moers", name: "Moers", state: "Nordrhein-Westfalen", population: 104000 },
  { slug: "trier", name: "Trier", state: "Rheinland-Pfalz", population: 110000 },
  { slug: "siegen", name: "Siegen", state: "Nordrhein-Westfalen", population: 102000 },
  { slug: "hildesheim", name: "Hildesheim", state: "Niedersachsen", population: 101000 },
  { slug: "salzgitter", name: "Salzgitter", state: "Niedersachsen", population: 101000 },
];

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug);
}
